feat: hyprpaper config, ansible vault

diff --git a/bin/archdot-install b/bin/archdot-install
--- a/bin/archdot-install
+++ b/bin/archdot-install
@@ -13,8 +13,27 @@ else
     cd ~/.archdot
 fi
 
+if [ ! -d ~/.ansible ]; then
+    mkdir ~/.ansible
+fi
+if [ ! -f ~/.ansible/vault_pass ]; then
+    touch ~/.ansible/vault_pass
+    chmod 600 ~/.ansible/vault_pass
+    read -p "Enter Ansible vault password: " VAULT_PASS
+    echo "$VAULT_PASS" > ~/.ansible/vault_pass
+fi
+if [ -z "$VAULT_PASS" ]; then
+    echo "Vault password cannot be empty. Exiting."
+    exit 1
+fi
+
 read -sp "Enter sudo password: " SUDO_PASS
+if [ -z "$SUDO_PASS" ]; then
+    echo "Sudo password cannot be empty. Exiting."
+    exit 1
+fi
+
 echo
 
 ansible-galaxy collection install -r requirements.yml
-ansible-playbook main.yml -e "ansible_become_password=${SUDO_PASS}"
+ansible-playbook main.yml -e "ansible_become_password=${SUDO_PASS}" --vault-password-file ~/.ansible/vault_pass
